<?php

require_once('src/BigInteger.php');
require_once('src/Srp6.class.php');

$action = $_POST["action"];

switch ($action) {
    case 'Initial':
        handleInitial($_POST["A"], $_POST["username"]);
    
    default:
        handleDefault($action);
        break;
}


function handleInitial($A, $username)
{
    $srp = new Srp6();

    // Get the v for Carol
    $v = getVFromDatabase($username);
    $srp->setV($v);

    $srp->calculateBandU($A);

    // to send
    $salt = getSaltFromDb($username);
    $B = $srp->getB();
    $u = $srp->getU();


    // to delete
    $srp->computeS($A);

    $ret = array(
        'status' => 'ok', 
        'salt' => $salt, 
        'B' => $B, 
        '_b' => $srp->getb_(),
        'u' => $u,
        'A' => $A,
        'serverKey' => $srp->getKey());

    die(json_encode($ret));
}

function handleDefault($action)
{
    die("Sorry, action: '$action' has not been implemented.");
}

function getVFromDatabase($username)
{
    // Generated by
    // $x = hash("sha256", "carols-salt" . "carols-password");
    // $v = $srp->generateV($x);

    // SELECT v from users where username = $username
    return "11b9bd6a59a1a7e9cbf51251542ef5a97c745ea4de2c6466e05f3606d8e27e953ca5ae5044a62a0ddd6e5263de8f144c845a657990ddcc29207111ce1e55b03cb5852039b87d05e342a633cbd5c54ba829a24096f58e21d3dc299e0d57e218b0a9e2fec3d6702417182df1d195c990ddcadfae9231e8d36d2f10dfa5b4732a3f";
}

function getSaltFromDb($username)
{
    // SELET salt from users where username = $username
    return "carols-salt";
}

/*
 * Take the modulus of $number
 */
function bigMod($number, $mod)
{
    return $number->modPow(new Math_BigInteger(1), $mod);
}
function hexToBigInt($string)
{
    // Remove : and all whitespace
    $string = str_replace(":","", $string);
    $string = preg_replace('/\s+/', '', $string);
    return new Math_BigInteger('0x' . $string, 16); 
}

?>